janus:
  restart: always
  build: .
  # image: efacilitation/docker-janus-webrtc-gateway
  container_name: a-janus
  volumes:
    - "~/docker-nginx-https/config/nginx/certs:/opt/janus/certs"
  ports:
    - "8081:8081"
    - "8081:8081"
  environment:
    - VIRTUAL_HOST=janus.yongbuzhixi.com
    - LETSENCRYPT_HOST=janus.yongbuzhixi.com
    - LETSENCRYPT_EMAIL=dale@yongbuzhixi.com